# Generated by Django 4.1.1 on 2022-10-02 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrolladora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('contacto', models.EmailField(blank=True, max_length=254)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('genero', models.CharField(max_length=50, verbose_name='genero')),
                ('fechaDeLanzamiento', models.DateField(verbose_name='fechaDeLanzamiento')),
                ('plataforma', models.CharField(blank=True, choices=[('Playstation 5', 'Playstation 5'), ('Xbox Series X/S', 'Xbox Series X/S'), ('Nintendo Switch', 'Nintendo Switch'), ('PC', 'PC'), ('Xbox 360', 'Xbox 360'), ('Nintendo DS', 'Nintendo DS'), ('Playstation 4', 'Playstation 4'), ('Playstation 3', 'Playstation 3'), ('Playstation 2', 'Playstation 2'), ('Playstation', 'Playstation'), ('Gameboy Advance', 'Gameboy Advance'), ('Gameboy', 'Gameboy'), ('Xbox', 'Xbox'), ('Xbox One', 'Xbox One'), ('Nintendo', 'Nintendo'), ('Super Nintendo', 'Super Nintendo'), ('Nintendo Wii', 'Nintendo Wii'), ('Nintendo 64', 'Nintendo 64'), ('Megadrive', 'Megadrive'), ('Nintendo Wii U', 'Nintendo Wii U')], max_length=50, null=True, verbose_name='plataforma')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
